#!/usr/bin/env python3
"""Fix shortfall - add more Specialist questions for Junior, Middle, Senior levels."""
import json

with open('/home/nhatbang/EXE101/PRJ/docs/crawl_data/marketing_specialist.json') as f:
    data = json.load(f)

additional_junior = [
    "How do you create a customer journey map?",
    "What is your experience with marketing automation workflows?",
    "How do you create a lead nurturing sequence?",
    "What is your approach to social media advertising?",
    "How do you optimize a Google Ads campaign?",
    "What is your experience with keyword research tools?",
    "How do you analyze competitor keywords?",
    "What is your approach to content gap analysis?",
    "How do you create a blog editorial calendar?",
    "What is your experience with guest blogging?",
    "How do you optimize content for featured snippets?",
    "What is your approach to internal linking strategy?",
    "How do you use Google Search Console to improve SEO?",
    "What is your experience with Google Data Studio?",
    "How do you create automated marketing reports?",
    "What is your approach to event marketing?",
    "How do you measure event ROI?",
    "What is your experience with trade show marketing?",
    "How do you create a webinar funnel?",
    "What is your approach to podcast marketing?",
    "How do you repurpose content across channels?",
    "What is your experience with content syndication?",
    "How do you create an ebook from blog content?",
    "What is your approach to gated content?",
    "How do you create a lead magnet that converts?",
    "What is your experience with exit-intent popups?",
    "How do you optimize forms for conversions?",
    "What is your approach to progressive profiling?",
    "How do you use chatbots in marketing?",
    "What is your experience with SMS marketing?",
    "How do you segment audiences for SMS campaigns?",
    "What is your approach to push notification marketing?",
    "How do you create a mobile app marketing strategy?",
    "What is your experience with app store optimization (ASO)?",
    "How do you measure app install campaign success?",
    "What is your approach to YouTube marketing?",
    "How do you optimize YouTube channel for growth?",
    "What is your experience with TikTok advertising?",
    "How do you create a TikTok content strategy?",
    "What is your approach to Instagram Reels marketing?",
    "How do you use LinkedIn for content distribution?",
    "What is your experience with LinkedIn Sales Navigator?",
    "How do you run LinkedIn lead gen forms?",
    "What is your approach to Twitter/X marketing?",
    "How do you use Twitter for customer service?",
    "What is your approach to Pinterest marketing?",
    "How do you optimize Pinterest boards for search?",
    "What is your experience with Reddit marketing?",
    "How do you engage with niche communities?",
    "What is your approach to forum marketing?",
    "How do you create a community from scratch?",
    "What is your experience with Discord marketing?",
    "How do you use Slack communities for marketing?",
    "What is your approach to podcast guesting?",
    "How do you pitch yourself for podcast interviews?",
    "What is your experience with HARO (Help A Reporter Out)?",
    "How do you build relationships with journalists?",
    "What is your approach to digital PR?",
    "How do you create a press kit?",
    "What is your experience with product seeding?",
    "How do you run a product sampling campaign?",
    "What is your approach to user-generated content campaigns?",
    "How do you incentivize user-generated content?",
    "What is your experience with customer reviews strategy?",
    "How do you manage Google Business Profile?",
    "What is your approach to local SEO?",
    "How do you optimize for voice search?",
    "How do you optimize for Google Maps?",
    "What is your experience with schema markup implementation?",
    "How do you conduct a technical SEO audit?",
    "What is your experience with site speed optimization?",
    "How do you improve Core Web Vitals?",
    "What is your approach to mobile-first indexing?",
    "How do you handle duplicate content issues?",
    "What is your experience with canonical tags?",
    "How do you manage URL structure for SEO?",
    "What is your approach to 404 error handling?",
    "How do you set up 301 redirects?",
    "What is your experience with hreflang tags for international SEO?",
    "How do you create content for multilingual SEO?",
    "What is your approach to video SEO?",
    "How do you optimize video transcripts for SEO?",
    "What is your experience with image SEO?",
    "How do you optimize alt text and file names for images?",
    "What is your approach to social media SEO?",
    "How do you optimize social media profiles for search?",
    "What is your experience with influencer content optimization?",
    "How do you collaborate with influencers on content?",
    "What is your approach to measuring influencer campaign success?",
    "How do you create an influencer brief?",
    "What is your experience with affiliate program management?",
    "How do you recruit affiliates?",
    "How do you optimize affiliate commission structures?",
    "What is your approach to tracking affiliate performance?",
    "How do you use coupon codes for tracking?",
    "What is your experience with partner marketing?",
    "How do you structure co-marketing partnerships?",
]

additional_middle = [
    "How do you design a multi-touch attribution model?",
    "What is your approach to marketing mix modeling?",
    "How do you use causal impact analysis in marketing?",
    "What is your experience with incrementality measurement?",
    "How do you conduct a holdout test?",
    "What is your approach to geo-lift testing?",
    "How do you design a randomized controlled trial in marketing?",
    "What is your experience with test-control methodology?",
    "How do you measure brand lift?",
    "What is your approach to brand health tracking?",
    "How do you build a brand tracker?",
    "What is your experience with conjoint analysis?",
    "How do you use MaxDiff analysis?",
    "What is your approach to survey design for market research?",
    "How do you analyze survey data?",
    "What is your experience with segmentation studies?",
    "How do you create a segmentation framework?",
    "How do you activate segments in marketing?",
    "What is your approach to personas development?",
    "How do you validate personas with data?",
    "What is your experience with jobs-to-be-done framework?",
    "How do you apply JTBD in marketing?",
    "What is your approach to customer advisory boards?",
    "How do you run customer focus groups?",
    "What is your experience with in-depth customer interviews?",
    "How do you synthesize qualitative research?",
    "What is your approach to competitive intelligence?",
    "How do you set up competitive monitoring?",
    "What is your experience with win/loss analysis?",
    "How do you conduct a win/loss interview?",
    "What is your approach to pricing research?",
    "How do you use Van Westendorp pricing analysis?",
    "What is your experience with Gabor-Granger pricing?",
    "How do you optimize pricing tiers?",
    "What is your approach to packaging strategy?",
    "How do you create product bundles?",
    "What is your experience with subscription pricing models?",
    "How do you optimize subscription pricing?",
    "What is your approach to freemium strategy?",
    "How do you convert free users to paid?",
    "What is your experience with trial optimization?",
    "How do you design a trial-to-paid conversion funnel?",
    "What is your approach to customer onboarding?",
    "How do you create an onboarding email sequence?",
    "What is your experience with product-led growth?",
    "How do you implement a PLG motion?",
    "What is your approach to self-serve marketing?",
    "How do you optimize product discovery?",
    "What is your experience with community-led growth?",
    "How do you build a community that drives acquisition?",
    "What is your approach to advocacy marketing?",
    "How do you scale a customer advocacy program?",
    "What is your experience with NPS programs?",
    "How do you close the loop with detractors?",
    "What is your approach to customer health scoring?",
    "How do you identify at-risk customers?",
    "What is your experience with churn analysis?",
    "How do you build a churn prediction model?",
    "What is your approach to retention marketing?",
    "How do you create a win-back campaign?",
    "What is your experience with re-engagement marketing?",
    "How do you measure re-engagement success?",
    "What is your approach to loyalty programs?",
    "How do you measure loyalty program ROI?",
    "How do you optimize loyalty program tiers?",
]

additional_senior = [
    "How do you build a marketing organization's strategic roadmap?",
    "What is your approach to enterprise marketing strategy?",
    "How do you manage marketing in a multinational corporation?",
    "What is your experience with marketing at the Fortune 500 level?",
    "How do you drive marketing innovation at scale?",
    "What is your approach to building a marketing lab?",
    "How do you create a culture of continuous improvement in marketing?",
    "What is your experience with Six Sigma in marketing?",
    "How do you apply lean methodology to marketing?",
    "What is your approach to marketing process optimization?",
    "How do you implement center of excellence in marketing?",
    "What is your experience with shared services in marketing?",
    "How do you manage a marketing shared service model?",
    "What is your approach to marketing outsourcing strategy?",
    "How do you decide what to outsource vs build in-house?",
    "What is your experience with near-shore and off-shore marketing teams?",
    "How do you manage a distributed marketing organization?",
    "What is your approach to marketing governance?",
    "How do you create marketing policies and standards?",
    "What is your experience with marketing compliance programs?",
    "How do you ensure regulatory compliance in marketing globally?",
    "What is your approach to marketing risk assessment?",
    "How do you build a risk framework for marketing?",
    "What is your experience with marketing audit programs?",
    "How do you conduct a marketing effectiveness audit?",
    "What is your approach to marketing performance management?",
    "How do you design marketing incentives and compensation?",
    "What is your experience with marketing balanced scorecard?",
    "How do you create a marketing strategy map?",
    "What is your approach to marketing portfolio management?",
    "How do you manage a portfolio of marketing investments?",
    "What is your experience with stage-gate process in marketing?",
    "How do you manage marketing project portfolio risk?",
    "What is your approach to new product development marketing?",
    "How do you integrate marketing into NPD process?",
    "What is your experience with design thinking in marketing?",
    "How do you apply design thinking to marketing problems?",
    "What is your approach to agile product marketing?",
    "How do you run a sprint for marketing?",
    "What is your experience with dual-track agile in marketing?",
    "How do you manage marketing in a DevOps environment?",
    "What is your approach to marketing in a platform business?",
    "How do you market platform products?",
    "What is your experience with marketplace marketing?",
    "How do you build network effects through marketing?",
    "What is your approach to API marketing?",
    "How do you market to developers?",
    "What is your experience with open source marketing?",
    "How do you build a developer community?",
    "What is your approach to SaaS marketing at scale?",
    "How do you manage marketing for multi-product SaaS?",
    "What is your experience with consumption-based pricing marketing?",
    "How do you market usage-based products?",
    "What is your approach to enterprise sales marketing?",
    "How do you create marketing for complex B2B sales?",
    "What is your experience with strategic account marketing?",
    "How do you create marketing programs for named accounts?",
    "What is your approach to executive engagement marketing?",
    "How do you create C-level marketing programs?",
    "What is your experience with board-level marketing communications?",
    "How do you prepare marketing materials for board meetings?",
    "What is your approach to investor marketing?",
    "How do you market to analysts?",
    "What is your experience with industry analyst relations?",
    "How do you manage the analyst relations function?",
    "What is your approach to government marketing?",
    "How do you market to government entities?",
    "What is your experience with public sector marketing?",
    "How do you navigate government procurement in marketing?",
    "What is your approach to non-profit marketing?",
    "How do you market for social impact?",
]

# Add to existing data
data['questions']['Junior'].extend(additional_junior)
data['questions']['Middle'].extend(additional_middle)
data['questions']['Senior'].extend(additional_senior)

# Deduplicate each level
for level in data['questions']:
    data['questions'][level] = list(set(data['questions'][level]))

# Check counts
for level, qs in data['questions'].items():
    print(f"Specialist {level}: {len(qs)} questions")

# Save
with open('/home/nhatbang/EXE101/PRJ/docs/crawl_data/marketing_specialist.json', 'w') as f:
    json.dump(data, f, indent=2)

print("\nUpdated marketing_specialist.json")
