#!/usr/bin/env python3
"""Generate comprehensive marketing interview questions JSON files.
Combines scraped questions with curated questions organized by level."""
import json
import re

# Load scraped questions
with open('/home/nhatbang/EXE101/PRJ/docs/crawl_data/raw_questions.json') as f:
    scraped = json.load(f)

# Clean scraped questions - filter out non-questions and ads
def is_valid_question(q):
    # Remove ads and junk
    skip_phrases = [
        'looking to enhance', 'are you ready to master', 'want to master',
        'want to learn from', 'looking for fresh', 'enrol in upGrad',
        'join upGrad', 'a complete guide to', '5 p\'s of marketing: how to make',
        'what is the smart method', 'how to ace a', 'how to nail a',
        'personal branding: how to build', 'what are competency-based',
        'what is the best answer for', 'what questions should i ask',
        'what\'s a good weakness', 'how to answer why',
        'how to create a personal blog', 'which is the best certification',
        'how long will content', 'how digital marketing helps',
        'what is marketing management', 'can ai-assisted',
        'what are the 8 p'
    ]
    ql = q.lower()
    for sp in skip_phrases:
        if sp in ql:
            return False
    # Must contain a question mark
    if '?' not in q:
        return False
    # Must be reasonable length
    if len(q) < 15 or len(q) > 400:
        return False
    return True

scraped_clean = [q for q in scraped if is_valid_question(q)]
print(f"Valid scraped questions: {len(scraped_clean)}")

# =============================================
# MARKETING SPECIALIST QUESTIONS BY LEVEL
# =============================================

specialist_intern = [
    "What is marketing?",
    "What is the difference between marketing and sales?",
    "What are the 4 Ps of marketing?",
    "What is a target market?",
    "What is a customer persona?",
    "What is market segmentation?",
    "What is the AIDA model in marketing?",
    "What is content marketing?",
    "What is SEO and why is it important?",
    "What is social media marketing?",
    "What is email marketing?",
    "What is a marketing campaign?",
    "What is brand awareness?",
    "What is a USP (Unique Selling Proposition)?",
    "What is a buyer's journey?",
    "What is a call-to-action (CTA)?",
    "What is a landing page?",
    "What is Google Analytics?",
    "What is a KPI in marketing?",
    "What is the difference between B2B and B2C marketing?",
    "What is influencer marketing?",
    "What are keywords in SEO?",
    "What is a marketing funnel?",
    "What is lead generation?",
    "What is conversion rate?",
    "What is organic traffic?",
    "What is paid advertising?",
    "What is a blog and why do companies blog?",
    "What is a newsletter?",
    "What is brand identity?",
    "What is customer retention?",
    "What is a SWOT analysis in marketing?",
    "What is the difference between branding and marketing?",
    "What is a value proposition?",
    "What is a hashtag used for in social media?",
    "What is viral marketing?",
    "What is affiliate marketing?",
    "What is a bounce rate in web analytics?",
    "What is click-through rate (CTR)?",
    "What is cost per click (CPC)?",
    "What is return on investment (ROI) in marketing?",
    "What is omnichannel marketing?",
    "What is a content calendar?",
    "What is A/B testing in marketing?",
    "What is a press release?",
    "What is a tagline?",
    "What are marketing demographics?",
    "What is psychographic segmentation?",
    "What is the difference between a strategy and a tactic?",
    "What is the role of a Marketing Specialist?",
    "What is Google AdWords?",
    "What is Facebook Ads Manager?",
    "What is an email autoresponder?",
    "What is a pay-per-click (PPC) campaign?",
    "What is search engine marketing (SEM)?",
    "What is a referral program?",
    "What is a customer loyalty program?",
    "What is a brand guideline?",
    "What are meta tags in SEO?",
    "What is backlinking?",
    "What is domain authority?",
    "What is page authority?",
    "What is anchor text in SEO?",
    "What is alt text in images?",
    "What is canonical URL?",
    "What is 301 redirect?",
    "What is XML sitemap?",
    "What is robots.txt file?",
    "What is Google Search Console?",
    "What is the difference between on-page and off-page SEO?",
    "What is a content management system (CMS)?",
    "What is WordPress?",
    "What is a plugin in WordPress?",
    "What is a theme in WordPress?",
    "What is an infographic?",
    "What is a whitepaper in marketing?",
    "What is an e-book in marketing?",
    "What is a case study in marketing?",
    "What is a webinar?",
    "What is a podcast?",
    "What is a CRM system?",
    "What is Mailchimp?",
    "What is Hootsuite?",
    "What is Canva?",
    "What is Adobe Photoshop used for in marketing?",
    "What is a storyboard?",
    "What is a mood board?",
    "What is the marketing mix?",
    "What are the 7 Ps of marketing?",
    "What is a customer journey map?",
    "What is a touchpoint in marketing?",
    "What is brand equity?",
    "What is brand positioning?",
    "What is guerilla marketing?",
    "What is word-of-mouth marketing?",
    "What is remarketing?",
    "What is a social media algorithm?",
    "What is engagement rate on social media?",
    "What is reach in social media?",
    "What is impressions in digital advertising?",
    "What is the difference between reach and impressions?",
    "What is a lookalike audience?",
    "What is a custom audience?",
    "What is retargeting?",
    "What is a marketing automation tool?",
    "What is drip marketing?",
    "What is lead scoring?",
    "What is the purpose of a FAQ page?",
]

specialist_fresher = [
    "How do you create a marketing plan for a new product?",
    "What steps would you follow to launch a social media campaign?",
    "How do you measure the success of a marketing campaign?",
    "What metrics are most important in email marketing?",
    "How do you write a compelling subject line for an email?",
    "What is your process for keyword research?",
    "How do you optimize a webpage for SEO?",
    "What tools do you use for social media management?",
    "How do you create engaging social media content?",
    "What is your approach to A/B testing?",
    "How do you analyze competitor marketing strategies?",
    "What is your experience with Google Analytics?",
    "How do you calculate customer acquisition cost (CAC)?",
    "How do you calculate customer lifetime value (CLV)?",
    "What is your understanding of buyer personas?",
    "How do you tailor content for different stages of the buyer's journey?",
    "What is the difference between inbound and outbound marketing?",
    "How do you create a content calendar?",
    "What is your process for writing a blog post?",
    "How do you promote a blog post?",
    "What is your experience with email marketing platforms?",
    "How do you segment an email list?",
    "What is a good open rate for email marketing?",
    "How do you improve email click-through rates?",
    "What is the role of storytelling in marketing?",
    "How do you create a brand voice?",
    "What is the purpose of a call-to-action?",
    "How do you design a landing page for conversions?",
    "What is AIDA model and how do you apply it?",
    "How do you set marketing goals and objectives?",
    "What is SMART framework in marketing?",
    "How do you report on marketing performance?",
    "What is a marketing dashboard?",
    "How do you handle negative comments on social media?",
    "What is your approach to content curation?",
    "How do you research industry trends?",
    "What is your experience with paid search advertising?",
    "How do you set up a Google Ads campaign?",
    "What is quality score in Google Ads?",
    "How do you optimize a PPC campaign?",
    "What is a long-tail keyword?",
    "What is the difference between broad match and exact match keywords?",
    "How do you optimize images for the web?",
    "What is your experience with video marketing?",
    "How do you create a social media posting schedule?",
    "What is the best time to post on social media?",
    "How do you identify influencers for a campaign?",
    "What is your approach to community management?",
    "How do you gather customer feedback for marketing?",
    "What is your experience with survey tools?",
    "How do you use customer testimonials in marketing?",
    "What is a case study and how do you write one?",
    "How do you create an infographic?",
    "What is your understanding of viral marketing?",
    "How do you create a shareable piece of content?",
    "What are the key elements of a successful social media post?",
    "How do you use emojis in marketing communications?",
    "What is the role of a FAQ page in marketing?",
    "How do you optimize a Google My Business profile?",
    "What is local SEO?",
    "How do you get customer reviews?",
    "What is the importance of mobile optimization in marketing?",
    "How do you create a mobile-friendly email?",
    "What is AMP in email marketing?",
    "How do you use storytelling in social media?",
    "What is a content upgrade?",
    "How do you create a lead magnet?",
    "What is a landing page vs a homepage?",
    "How do you write ad copy?",
    "What is the difference between display ads and search ads?",
    "How do you target audiences on Facebook?",
    "What is the Facebook pixel?",
    "How do you track conversions with Facebook Pixel?",
    "What is retargeting and how does it work?",
    "What is your understanding of account-based marketing?",
    "How do you create a buyer persona for B2B marketing?",
    "What is LinkedIn marketing?",
    "How do you use LinkedIn for B2B lead generation?",
    "What is Twitter marketing best practices?",
    "How do you use Instagram for brand awareness?",
    "What is Instagram Stories and how do brands use it?",
    "What is TikTok marketing?",
    "How do you create content for TikTok?",
    "What is Pinterest marketing?",
    "What is YouTube marketing?",
    "How do you optimize YouTube videos for search?",
    "What is a video description and why is it important?",
    "How do you create a YouTube thumbnail?",
    "What is the role of hashtags in Instagram marketing?",
    "How many hashtags should you use on Instagram?",
    "What is your experience with Reddit marketing?",
    "What is the difference between a Facebook Page and a Facebook Group?",
    "How do you grow a Facebook Group?",
    "What is your experience with Google Tag Manager?",
    "How do you set up conversion tracking in Google Analytics?",
    "What is a goal in Google Analytics?",
    "What is the difference between a session and a pageview?",
    "How do you analyze website traffic sources?",
    "What is the bounce rate and how do you improve it?",
    "What is average session duration?",
    "How do you use UTM parameters?",
]

specialist_junior = [
    "How do you develop a comprehensive marketing strategy?",
    "Can you describe a successful marketing campaign you managed?",
    "How do you integrate multiple marketing channels in a campaign?",
    "What is your experience with marketing automation platforms?",
    "How do you score and qualify leads?",
    "What is your approach to budget allocation across marketing channels?",
    "How do you optimize conversion rates across the marketing funnel?",
    "What is your process for competitive analysis?",
    "How do you use data to drive marketing decisions?",
    "Describe a time you turned around an underperforming campaign.",
    "How do you handle stakeholder communication for marketing projects?",
    "What is your experience with CRM integration in marketing?",
    "How do you align marketing content with sales objectives?",
    "What techniques do you use for customer retention marketing?",
    "How do you approach lifecycle marketing?",
    "What is your experience with marketing analytics and attribution?",
    "How do you calculate and optimize ROAS (Return on Ad Spend)?",
    "What is multi-touch attribution in marketing?",
    "How do you manage a content marketing team?",
    "What is your approach to SEO strategy beyond keywords?",
    "How do you conduct technical SEO audits?",
    "What is your experience with structured data and schema markup?",
    "How do you build backlinks for SEO?",
    "What is your approach to PR and earned media?",
    "How do you handle a product recall from a marketing perspective?",
    "Describe a time you used A/B testing to improve campaign performance.",
    "How do you segment audiences for personalized marketing?",
    "What is your experience with dynamic content personalization?",
    "How do you create an omnichannel customer experience?",
    "What is your approach to budget forecasting in marketing?",
    "How do you measure brand awareness quantitatively?",
    "What is net promoter score (NPS) and how do you use it?",
    "How do you analyze customer churn and implement retention strategies?",
    "What is your experience with marketing to different generations?",
    "How do you localize marketing content for different regions?",
    "What is your approach to crisis communication in marketing?",
    "How do you respond to a PR crisis?",
    "What is your experience with growth hacking techniques?",
    "How do you run a viral marketing campaign intentionally?",
    "What is your understanding of the product-market fit concept?",
    "How do you validate marketing hypotheses?",
    "What is your experience with marketing experiments?",
    "How do you prioritize marketing initiatives with limited resources?",
    "What frameworks do you use for marketing prioritization?",
    "How do you create a go-to-market strategy?",
    "What is your experience with product launches?",
    "How do you create product messaging that resonates?",
    "What is your approach to pricing strategy in marketing?",
    "How do you conduct price sensitivity analysis?",
    "What is your experience with affiliate marketing programs?",
    "How do you manage relationships with external agencies?",
    "What is your approach to creative briefs?",
    "How do you evaluate creative work?",
    "What is your experience with video production for marketing?",
    "How do you measure the impact of influencer marketing?",
    "What is your approach to selecting influencers for a campaign?",
    "How do you manage social media contests and giveaways?",
    "What is your experience with user-generated content campaigns?",
    "How do you encourage user-generated content?",
    "What is your approach to building an email nurture sequence?",
    "How do you create a lead scoring model?",
    "What is your experience with marketing CRM platforms like HubSpot or Salesforce?",
    "How do you create a marketing automation workflow?",
    "What is your experience with webinars as a marketing channel?",
    "How do you promote a webinar?",
    "What is your experience with podcast marketing?",
    "How do you measure the effectiveness of event marketing?",
    "What is your approach to trade show marketing?",
    "How do you create a banner ad that performs?",
    "What is your experience with programmatic advertising?",
    "How do you optimize display advertising campaigns?",
    "What is your understanding of ad exchanges and DSPs?",
    "How do you use heatmaps and session recordings in marketing?",
    "What is your experience with CRO (Conversion Rate Optimization)?",
    "How do you run a CRO experiment?",
    "What is your approach to customer onboarding marketing?",
    "How do you create a customer advocacy program?",
    "What is your experience with referral marketing programs?",
    "How do you track and measure word-of-mouth marketing?",
    "What is your experience with marketing in regulated industries?",
    "How do you ensure marketing compliance (GDPR, CAN-SPAM)?",
    "What is your understanding of data privacy in marketing?",
    "How do you obtain marketing consent properly?",
    "What is your experience with survey design and analysis?",
    "How do you create a Net Promoter Survey?",
    "What is your experience with social listening tools?",
    "How do you use social listening for market research?",
    "What is sentiment analysis in marketing?",
    "How do you report marketing results to executives?",
    "What is your approach to creating executive dashboards?",
    "How do you align marketing KPIs with business goals?",
    "What is your experience with OKRs in marketing?",
    "How do you set up a marketing attribution model?",
    "What is your experience with first-touch vs last-touch attribution?",
    "How do you calculate marketing contribution to pipeline?",
    "What is marketing qualified lead (MQL) vs sales qualified lead (SQL)?",
    "How do you define and measure engagement?",
]

specialist_middle = [
    "How do you design a multi-channel marketing strategy from scratch?",
    "What is your framework for developing a yearly marketing plan?",
    "How do you allocate a marketing budget of over $1M across channels?",
    "What metrics do you use to decide channel allocation?",
    "How do you build a marketing technology stack?",
    "What is your experience with CDP (Customer Data Platform)?",
    "How do you integrate marketing automation with CRM?",
    "What is your approach to API-based marketing integrations?",
    "How do you manage marketing data quality?",
    "What is your experience with predictive analytics in marketing?",
    "How do you implement AI and machine learning in marketing?",
    "What is your experience with chatbots in marketing?",
    "How do you personalize at scale?",
    "What is your approach to 1:1 marketing?",
    "How do you handle data silos in marketing?",
    "What is your experience with marketing attribution modeling?",
    "How do you build a custom attribution model?",
    "What is the role of incrementality testing in marketing?",
    "How do you measure the incremental lift of a campaign?",
    "What is your experience with media mix modeling (MMM)?",
    "How do you balance brand building vs performance marketing?",
    "What is your approach to long-term brand strategy?",
    "How do you measure brand health over time?",
    "What is your experience with brand tracking studies?",
    "How do you manage brand architecture across multiple products?",
    "What is your approach to rebranding?",
    "How do you handle brand positioning in a competitive market?",
    "What is your experience with co-branding partnerships?",
    "How do you evaluate sponsorship opportunities?",
    "What is your approach to cause marketing?",
    "How do you integrate sustainability into marketing strategy?",
    "What is your experience with marketing during a recession?",
    "How do you pivot marketing strategy in response to market changes?",
    "What is your approach to competitor response strategy?",
    "How do you handle a competitive threat in the market?",
    "What is your experience with market entry strategies?",
    "How do you create a go-to-market plan for a new market segment?",
    "What is your approach to international marketing expansion?",
    "How do you adapt marketing for different cultural contexts?",
    "What is your experience with global campaign management?",
    "How do you ensure consistent brand messaging globally?",
    "What is your approach to managing a distributed marketing team?",
    "How do you mentor junior marketing team members?",
    "What is your experience with hiring marketing talent?",
    "How do you evaluate marketing team performance?",
    "What is your approach to cross-functional collaboration in marketing?",
    "How do you work with product teams on go-to-market?",
    "How do you collaborate with sales on lead handoff?",
    "What is your approach to sales enablement?",
    "How do you create sales collateral that works?",
    "What is your experience with marketing-sales alignment (smarketing)?",
    "How do you implement a service level agreement (SLA) between marketing and sales?",
    "What is your approach to marketing operations?",
    "How do you optimize marketing workflows?",
    "What is your experience with agile marketing methodologies?",
    "How do you implement scrum in marketing?",
    "What is your approach to marketing project management?",
    "How do you manage multiple marketing projects simultaneously?",
    "What is your experience with marketing resource management tools?",
    "How do you prioritize marketing requests from different stakeholders?",
    "What is your approach to vendor management in marketing?",
    "How do you evaluate and select marketing agencies?",
    "What is your experience with contract negotiation for marketing services?",
    "How do you measure agency performance?",
    "What is your approach to content strategy at scale?",
    "How do you create a content distribution strategy?",
    "What is your experience with content syndication?",
    "How do you repurpose content across channels effectively?",
    "What is your approach to thought leadership marketing?",
    "How do you build an executive thought leadership program?",
    "What is your experience with account-based marketing (ABM) at scale?",
    "How do you run an ABM program for enterprise accounts?",
    "What is your approach to intent data in marketing?",
    "How do you use third-party intent data?",
    "What is your experience with chatbots and conversational marketing?",
    "How do you implement a conversational marketing strategy?",
    "What is your approach to video marketing strategy?",
    "How do you create a YouTube channel strategy for a brand?",
    "What is your experience with live streaming for marketing?",
    "How do you measure video marketing ROI?",
    "What is your approach to audio marketing and podcasts?",
    "How do you create a branded podcast strategy?",
    "What is your experience with augmented reality in marketing?",
    "How do you evaluate emerging marketing technologies?",
    "What is your framework for adopting new marketing channels?",
    "How do you stay ahead of marketing technology trends?",
    "What is your approach to privacy-first marketing?",
    "How do you adapt to cookie-less tracking?",
    "What is your experience with first-party data strategies?",
    "How do you build a zero-party data collection strategy?",
    "What is your approach to ethical marketing?",
    "How do you handle marketing in a highly regulated industry?",
    "What is your experience with FDA or financial services marketing compliance?",
    "How do you audit marketing content for compliance?",
    "What is your approach to crisis management planning?",
    "How do you create a crisis communication plan?",
    "What is your experience with reputation management?",
    "How do you manage online reviews at scale?",
]

specialist_senior = [
    "How do you develop a 3-5 year marketing vision and strategy?",
    "What is your approach to transforming a marketing organization?",
    "How do you drive digital transformation in marketing?",
    "What is your experience with building a marketing department from scratch?",
    "How do you design organizational structure for a marketing team?",
    "What is your approach to talent development and succession planning in marketing?",
    "How do you create a marketing culture of experimentation?",
    "What is your experience with marketing M&A integration?",
    "How do you integrate marketing after a company acquisition?",
    "What is your approach to marketing during a company turnaround?",
    "How do you manage marketing during hyper-growth?",
    "What is your experience with IPO marketing readiness?",
    "How do you align marketing strategy with corporate strategy?",
    "What is your approach to board-level marketing communications?",
    "How do you present marketing strategy to the board of directors?",
    "What metrics do you report to the C-suite?",
    "How do you connect marketing spend to business outcomes?",
    "What is your approach to marketing investment ROI modeling?",
    "How do you justify marketing budget to the CFO?",
    "What is your experience with marketing P&L management?",
    "How do you build a business case for new marketing initiatives?",
    "What is your approach to strategic partnerships in marketing?",
    "How do you evaluate build vs buy decisions in marketing technology?",
    "What is your experience with marketing venture capital or funding?",
    "How do you create a marketing innovation pipeline?",
    "What is your approach to disruptive marketing strategy?",
    "How do you identify and capitalize on market disruptions?",
    "What is your experience with category creation marketing?",
    "How do you create a new market category?",
    "What is your approach to competitive disruption?",
    "How do you respond to a disruptive competitor?",
    "What is your experience with blue ocean strategy in marketing?",
    "How do you balance short-term results with long-term brand building?",
    "What is your framework for strategic marketing decisions?",
    "How do you make high-stakes marketing bets?",
    "What is your approach to risk management in marketing?",
    "How do you handle marketing failure at scale?",
    "What is your experience with post-mortem analysis of marketing campaigns?",
    "How do you foster innovation in a mature marketing team?",
    "What is your approach to intrapreneurship in marketing?",
    "How do you create a test-and-learn culture in marketing?",
    "What is your experience with marketing at a global scale?",
    "How do you manage marketing across different time zones and cultures?",
    "What is your approach to global brand consistency vs local relevance?",
    "How do you create a global-local marketing operating model?",
    "What is your experience with managing regional marketing teams?",
    "How do you build a center of excellence (CoE) in marketing?",
    "What is your approach to marketing capability building?",
    "How do you upskill your marketing team for future needs?",
    "What is your vision for the future of marketing?",
    "How do you think AI will transform marketing in the next 5 years?",
    "What is your experience with quantum marketing concepts?",
    "How do you prepare your marketing organization for Web3?",
    "What is your approach to metaverse marketing?",
    "How do you evaluate NFTs as a marketing tool?",
    "What is your experience with decentralized marketing?",
    "How do you incorporate blockchain in marketing?",
    "What is your approach to data ethics and governance in marketing?",
    "How do you build trust with consumers in a privacy-first world?",
    "What is your strategy for zero-party data collection?",
    "How do you create value exchange in data collection?",
    "What is your approach to consent management at scale?",
    "How do you balance personalization with privacy?",
    "What is your experience with data clean rooms in marketing?",
    "How do you collaborate with competitors on industry marketing standards?",
    "What is your approach to industry thought leadership?",
    "How do you build a brand that stands for something?",
    "What is your approach to brand activism?",
    "How do you navigate political and social issues in marketing?",
    "What is your experience with purpose-driven marketing?",
    "How do you measure the business impact of purpose marketing?",
    "What is your approach to DEI (Diversity, Equity, Inclusion) in marketing?",
    "How do you ensure inclusive marketing content?",
    "What is your experience with accessible marketing practices?",
    "How do you make marketing content accessible (ADA compliance)?",
    "What is your approach to sustainable marketing practices?",
    "How do you reduce the carbon footprint of marketing operations?",
    "What is your experience with circular economy marketing?",
    "How do you integrate ESG into marketing strategy?",
    "What is your approach to stakeholder marketing?",
    "How do you balance the needs of different stakeholders in marketing?",
    "What is your experience with employee advocacy programs?",
    "How do you turn employees into brand ambassadors?",
    "What is your approach to building a community-driven brand?",
    "How do you scale community marketing?",
    "What is your experience with customer advisory boards?",
    "How do you leverage customer communities for marketing insights?",
    "What is your approach to co-creation with customers?",
    "How do you involve customers in product development through marketing?",
    "What is your experience with crowdsourcing in marketing?",
    "How do you manage a brand in the age of customer empowerment?",
    "What is your approach to dealing with customer criticism going viral?",
    "How do you build brand resilience?",
    "What is your experience with marketing during a public relations crisis?",
    "How do you rebuild brand trust after a crisis?",
    "What is your approach to scenario planning in marketing?",
    "How do you prepare marketing strategies for different economic scenarios?",
    "What is your experience with war gaming in marketing strategy?",
]

print(f"Specialist Intern: {len(specialist_intern)}")
print(f"Specialist Fresher: {len(specialist_fresher)}")
print(f"Specialist Junior: {len(specialist_junior)}")
print(f"Specialist Middle: {len(specialist_middle)}")
print(f"Specialist Senior: {len(specialist_senior)}")

# =============================================
# MARKETING MANAGER QUESTIONS BY LEVEL
# =============================================

manager_intern = [
    "What does a Marketing Manager do?",
    "What is the difference between a Marketing Specialist and a Marketing Manager?",
    "What is a marketing plan?",
    "What are the key components of a marketing strategy?",
    "What is market research and why is it important?",
    "What is the marketing mix?",
    "What are the 4 Ps of marketing?",
    "What is brand management?",
    "What is a target audience?",
    "How do you identify a target audience?",
    "What is market segmentation?",
    "What is a SWOT analysis?",
    "What is a competitive analysis?",
    "What is a value proposition?",
    "What is a unique selling proposition (USP)?",
    "What is product positioning?",
    "What is brand positioning?",
    "What is a marketing objective?",
    "What is the difference between a goal and an objective?",
    "What are SMART objectives?",
    "What is a budget in marketing?",
    "What is ROI in marketing?",
    "What is a KPI?",
    "What is the difference between a strategy and a tactic?",
    "What is a campaign?",
    "What is integrated marketing communications?",
    "What is the AIDA model?",
    "What is a marketing channel?",
    "What is digital marketing?",
    "What is traditional marketing?",
    "What is the difference between above-the-line and below-the-line marketing?",
    "What is direct marketing?",
    "What is indirect marketing?",
    "What is relationship marketing?",
    "What is customer relationship management (CRM)?",
    "What is customer lifetime value (CLV or LTV)?",
    "What is customer acquisition cost (CAC)?",
    "What is brand equity?",
    "What is brand awareness?",
    "What is brand loyalty?",
    "What is brand extension?",
    "What is co-branding?",
    "What is a brand audit?",
    "What is a perceptual map?",
    "What is a positioning statement?",
    "What is a tagline?",
    "What is a slogan?",
    "What is a mission statement?",
    "What is a vision statement?",
    "What is corporate social responsibility (CSR) in marketing?",
    "What is cause marketing?",
    "What is green marketing?",
    "What is viral marketing?",
    "What is word-of-mouth marketing?",
    "What is referral marketing?",
    "What is affiliate marketing?",
    "What is influencer marketing?",
    "What is content marketing?",
    "What is inbound marketing?",
    "What is outbound marketing?",
    "What is permission marketing?",
    "What is interruption marketing?",
    "What is the marketing funnel?",
    "What is the buyer's journey?",
    "What is a lead?",
    "What is a prospect?",
    "What is a qualified lead?",
    "What is lead generation?",
    "What is lead nurturing?",
    "What is conversion rate?",
    "What is a call-to-action (CTA)?",
    "What is a landing page?",
    "What is a microsite?",
    "What is A/B testing?",
    "What is multivariate testing?",
    "What is market penetration?",
    "What is market development?",
    "What is product development?",
    "What is diversification?",
    "What is the Ansoff Matrix?",
    "What is the BCG Matrix?",
    "What is PESTLE analysis?",
    "What is Porter's Five Forces?",
    "What is a market challenger strategy?",
    "What is a market leader strategy?",
    "What is a market follower strategy?",
    "What is a niche market strategy?",
    "What is guerilla marketing?",
    "What is experiential marketing?",
    "What is event marketing?",
    "What is trade marketing?",
    "What is retail marketing?",
    "What is B2B marketing?",
    "What is B2C marketing?",
    "What is D2C (direct-to-consumer) marketing?",
    "What is omnichannel marketing?",
    "What is multichannel marketing?",
    "What is cross-channel marketing?",
    "What is social media marketing?",
    "What is email marketing?",
    "What is search engine marketing (SEM)?",
    "What is search engine optimization (SEO)?",
    "What is pay-per-click (PPC) advertising?",
    "What is display advertising?",
]

manager_fresher = [
    "How do you create a marketing plan for a new product launch?",
    "What steps do you follow when developing a marketing strategy?",
    "How do you conduct market research?",
    "What is your approach to competitor analysis?",
    "How do you segment a market?",
    "How do you select a target market?",
    "What is your process for developing a positioning strategy?",
    "How do you create a brand positioning statement?",
    "How do you set marketing budgets?",
    "What factors influence your marketing budget decisions?",
    "How do you measure the success of a marketing campaign?",
    "What metrics do you track for a product launch?",
    "How do you calculate customer acquisition cost?",
    "How do you calculate customer lifetime value?",
    "What is a good CAC/LTV ratio?",
    "How do you improve ROI on marketing spend?",
    "How do you create buyer personas?",
    "What information goes into a buyer persona?",
    "How do you map the customer journey?",
    "What are the stages of the customer journey?",
    "How do you identify customer pain points?",
    "How do you create a value proposition?",
    "How do you test a value proposition?",
    "How do you create a marketing calendar?",
    "What is your approach to content strategy?",
    "How do you create content for different stages of the funnel?",
    "What channels do you consider for content distribution?",
    "How do you manage a content calendar?",
    "How do you measure content marketing effectiveness?",
    "What is your experience with social media advertising?",
    "How do you create a social media strategy?",
    "What platforms would you recommend for different business types?",
    "How do you measure social media ROI?",
    "What is your approach to email marketing strategy?",
    "How do you build an email list?",
    "How do you segment an email list?",
    "What are email marketing best practices?",
    "How do you measure email marketing success?",
    "What is your approach to SEO strategy?",
    "How do you conduct keyword research?",
    "What on-page SEO factors matter most?",
    "How do you build a link building strategy?",
    "How do you measure SEO success?",
    "What is your approach to paid advertising?",
    "How do you set up a Google Ads campaign?",
    "What is your approach to bidding strategy in PPC?",
    "How do you optimize ad copy?",
    "How do you measure PPC success?",
    "What is your experience with Facebook advertising?",
    "How do you create a Facebook ad campaign?",
    "How do you target audiences on Facebook?",
    "What is your approach to LinkedIn advertising?",
    "How do you use LinkedIn for B2B marketing?",
    "What is your approach to marketing analytics?",
    "What tools do you use for marketing analytics?",
    "How do you create a marketing dashboard?",
    "What KPIs do you report to management?",
    "How do you interpret marketing data?",
    "How do you present marketing results?",
    "How do you work with external agencies?",
    "How do you brief a creative agency?",
    "How do you evaluate agency performance?",
    "What is your approach to budgeting for events?",
    "How do you plan a product launch event?",
    "How do you measure event marketing success?",
    "What is your approach to public relations?",
    "How do you write a press release?",
    "How do you build relationships with journalists?",
    "What is your approach to crisis communication?",
    "How do you handle negative press?",
    "What is your experience with marketing across different cultures?",
    "How do you adapt marketing for local markets?",
    "What is your approach to seasonal marketing?",
    "How do you plan marketing around holidays?",
    "How do you create urgency in marketing campaigns?",
    "What is scarcity marketing?",
    "How do you use social proof in marketing?",
    "What is your approach to customer testimonials?",
    "How do you collect customer case studies?",
    "How do you use user-generated content?",
    "What is your approach to partnership marketing?",
    "How do you identify potential marketing partners?",
    "How do you structure a co-marketing agreement?",
    "How do you create a referral program?",
    "What makes a good referral program?",
    "How do you measure referral program success?",
    "What is your approach to mobile marketing?",
    "How do you optimize for mobile?",
    "What is SMS marketing?",
    "How do you use push notifications in marketing?",
    "What is your approach to video marketing?",
    "How do you create a video marketing strategy?",
    "What types of video content work best for marketing?",
    "How do you measure video marketing success?",
    "What is your approach to podcast marketing?",
    "How do you create a branded podcast?",
    "How do you market a podcast?",
    "What is your approach to webinars?",
    "How do you create a successful webinar?",
    "How do you promote a webinar?",
]

manager_junior = [
    "How do you develop a comprehensive marketing strategy for a fiscal year?",
    "How do you align marketing strategy with overall business objectives?",
    "What is your framework for strategic marketing planning?",
    "How do you allocate resources across different marketing initiatives?",
    "What criteria do you use to prioritize marketing projects?",
    "How do you manage a marketing team?",
    "What is your management style?",
    "How do you motivate your marketing team?",
    "How do you set goals for your marketing team?",
    "How do you evaluate team member performance?",
    "How do you handle underperformance on your team?",
    "What is your approach to hiring marketing talent?",
    "How do you onboard new marketing team members?",
    "How do you foster collaboration in a marketing team?",
    "How do you manage cross-functional relationships?",
    "How do you work with the sales team?",
    "How do you resolve conflicts between marketing and sales?",
    "What is your approach to marketing-sales alignment?",
    "How do you create a service level agreement with sales?",
    "How do you manage relationships with product teams?",
    "How do you collaborate with product on go-to-market?",
    "How do you communicate marketing strategy to stakeholders?",
    "How do you get buy-in for marketing initiatives?",
    "How do you influence without authority in marketing?",
    "How do you manage a marketing budget?",
    "How do you track budget utilization?",
    "What do you do when a campaign goes over budget?",
    "How do you make budget trade-off decisions?",
    "How do you justify marketing spend to executives?",
    "What is your experience with marketing automation?",
    "How do you implement marketing automation?",
    "What is your approach to lead scoring?",
    "How do you design a lead nurturing workflow?",
    "How do you measure marketing automation ROI?",
    "What is your experience with CRM in marketing?",
    "How do you integrate marketing and sales in CRM?",
    "What is your approach to marketing analytics and reporting?",
    "How do you set up marketing dashboards?",
    "What tools do you use for marketing reporting?",
    "How do you track marketing attribution?",
    "What attribution model do you prefer and why?",
    "How do you handle multi-touch attribution?",
    "How do you measure brand lift?",
    "What is your approach to brand tracking?",
    "How do you conduct a brand audit?",
    "How do you measure brand awareness?",
    "What is your approach to rebranding?",
    "How do you manage a rebranding project?",
    "What is your experience with naming and brand architecture?",
    "How do you create brand guidelines?",
    "How do you ensure brand consistency?",
    "What is your approach to product launches?",
    "How do you create a go-to-market plan?",
    "What elements go into a launch plan?",
    "How do you coordinate cross-functional launch activities?",
    "How do you measure launch success?",
    "What is your approach to product marketing?",
    "How do you develop product messaging?",
    "What is your experience with pricing strategy?",
    "How do you conduct pricing research?",
    "How do you communicate value through pricing?",
    "What is your approach to competitive strategy?",
    "How do you monitor competitors?",
    "How do you respond to competitive threats?",
    "How do you differentiate in a crowded market?",
    "What is your approach to market research?",
    "How do you design a market research study?",
    "What is your experience with qualitative research?",
    "What is your experience with quantitative research?",
    "How do you turn research insights into marketing action?",
    "What is your approach to customer insights?",
    "How do you gather customer insights?",
    "How do you use customer feedback in marketing?",
    "What is your approach to customer retention?",
    "How do you design customer loyalty programs?",
    "How do you measure customer retention?",
    "What is your approach to customer experience marketing?",
    "How do you map and optimize customer touchpoints?",
    "How do you manage customer expectations through marketing?",
    "What is your approach to digital transformation in marketing?",
    "How do you evaluate new marketing technologies?",
    "What is your approach to adopting AI in marketing?",
    "How do you manage marketing technology stack?",
    "What is your experience with marketing data integration?",
    "How do you ensure data quality in marketing?",
    "What is your approach to privacy and data compliance?",
    "How do you adapt marketing to privacy regulations?",
    "What is your experience with GDPR, CCPA compliance?",
    "How do you handle cookie deprecation in your marketing strategy?",
    "What is your approach to first-party data strategy?",
    "How do you build a zero-party data strategy?",
    "What is your experience with account-based marketing?",
    "How do you design an ABM program?",
    "What is one-to-one vs one-to-few vs one-to-many in ABM?",
    "How do you measure ABM success?",
    "What is your approach to demand generation?",
    "How do you create a demand generation engine?",
    "What channels work best for demand generation?",
    "How do you measure demand generation effectiveness?",
    "How do you manage the handoff from marketing to sales?",
]

manager_middle = [
    "How do you develop a 1-2 year marketing roadmap?",
    "What is your process for strategic planning in marketing?",
    "How do you conduct a marketing audit?",
    "How do you evaluate the effectiveness of current marketing strategies?",
    "What frameworks do you use for marketing strategy development?",
    "How do you manage a portfolio of brands or products?",
    "What is your approach to brand portfolio strategy?",
    "How do you decide when to sunset a brand or product?",
    "How do you manage product life cycle marketing?",
    "What strategies do you use at each stage of the product life cycle?",
    "How do you handle marketing for declining products?",
    "What is your approach to marketing innovation?",
    "How do you foster innovation in the marketing team?",
    "How do you evaluate new marketing opportunities?",
    "What is your approach to testing new marketing channels?",
    "How do you scale a successful marketing pilot?",
    "How do you manage marketing operations?",
    "What is your experience with marketing operations?",
    "How do you optimize marketing processes?",
    "What is your approach to marketing workflow automation?",
    "How do you implement agile marketing?",
    "What is your experience with OKRs in marketing?",
    "How do you set and cascade marketing OKRs?",
    "How do you track progress against marketing goals?",
    "How do you handle underperforming marketing channels?",
    "When do you decide to cut a marketing channel?",
    "How do you optimize channel mix?",
    "What is your approach to media planning?",
    "How do you create a media plan?",
    "How do you negotiate with media vendors?",
    "What is your approach to programmatic media buying?",
    "How do you measure media effectiveness?",
    "What is your experience with marketing in different regions?",
    "How do you adapt a global campaign for local markets?",
    "How do you balance global brand consistency with local relevance?",
    "What is your experience with managing regional marketing teams?",
    "How do you build a global marketing function?",
    "What is your approach to international market entry?",
    "How do you prioritize international markets?",
    "What factors do you consider when entering a new market?",
    "How do you build brand awareness in a new market?",
    "What is your approach to leading a marketing team?",
    "How do you develop leadership in your marketing team?",
    "How do you create a high-performing marketing culture?",
    "What is your approach to talent retention in marketing?",
    "How do you manage remote or hybrid marketing teams?",
    "How do you handle difficult conversations in the team?",
    "How do you manage up in marketing leadership?",
    "How do you communicate marketing performance to the C-suite?",
    "How do you handle competing priorities from executives?",
    "What is your approach to stakeholder management in marketing?",
    "How do you manage agency and vendor relationships?",
    "How do you select and evaluate marketing agencies?",
    "How do you negotiate marketing contracts?",
    "How do you manage a marketing RFP process?",
    "What is your approach to insourcing vs outsourcing marketing?",
    "How do you manage large-scale marketing campaigns?",
    "What is your approach to campaign project management?",
    "How do you coordinate across multiple agencies?",
    "How do you ensure campaign consistency across channels?",
    "How do you manage campaign timelines and deliverables?",
    "What is your approach to integrated marketing campaigns?",
    "How do you create a seamless customer experience across channels?",
    "How do you orchestrate marketing across online and offline channels?",
    "What is your experience with experiential marketing at scale?",
    "How do you create an immersive brand experience?",
    "How do you measure experiential marketing ROI?",
    "What is your approach to sponsorships and partnerships?",
    "How do you evaluate sponsorship opportunities?",
    "How do you activate a sponsorship?",
    "How do you measure sponsorship ROI?",
    "What is your approach to cause marketing and CSR?",
    "How do you integrate purpose into brand marketing?",
    "How do you measure impact of cause marketing?",
    "What is your approach to sustainability marketing?",
    "How do you communicate sustainability efforts authentically?",
    "How do you avoid greenwashing?",
    "What is your approach to crisis management in marketing?",
    "How do you prepare for potential brand crises?",
    "How do you lead through a marketing crisis?",
    "How do you rebuild brand trust after a crisis?",
    "What is your experience with reputation management at scale?",
    "How do you manage a reputation crisis?",
    "How do you handle organized boycotts or negative campaigns?",
    "What is your approach to influencer strategy?",
    "How do you build an influencer program at scale?",
    "How do you measure influencer marketing ROI?",
    "What is your experience with celebrity endorsements?",
    "How do you manage influencer relationships?",
    "What is your approach to content strategy at scale?",
    "How do you build a content studio or agency model?",
    "How do you manage content production workflows?",
    "How do you measure content marketing ROI at scale?",
    "What is your approach to marketing data and analytics?",
    "How do you build a marketing analytics function?",
    "What is your experience with building a CDP (Customer Data Platform)?",
    "How do you use predictive analytics in marketing?",
    "How do you implement AI in marketing operations?",
    "What is your approach to marketing personalization at scale?",
    "How do you balance personalization and privacy?",
    "How do you implement real-time personalization?",
    "What is your experience with dynamic creative optimization?",
    "How do you manage marketing during economic uncertainty?",
    "How do you adapt marketing strategy during a recession?",
    "How do you protect marketing budget in downturns?",
    "How do you pivot marketing in response to market disruption?",
]

manager_senior = [
    "How do you develop a 3-5 year marketing vision?",
    "What is your approach to corporate strategy from a marketing perspective?",
    "How do you create a marketing strategy that drives business growth?",
    "How do you align marketing strategy with corporate strategy?",
    "How do you present marketing strategy to the board?",
    "What is your experience with marketing M&A?",
    "How do you integrate marketing after an acquisition?",
    "How do you conduct due diligence on marketing for acquisitions?",
    "What is your experience with IPO marketing?",
    "How do you prepare a company for IPO from a marketing perspective?",
    "How do you build a marketing organization from scratch?",
    "What organizational structure do you recommend for marketing?",
    "How do you design a marketing operating model?",
    "How do you build a high-performance marketing culture?",
    "What is your approach to talent strategy in marketing?",
    "How do you develop future marketing leaders?",
    "What is your approach to compensation and incentives for marketing?",
    "How do you manage a global marketing team?",
    "How do you build a global marketing center of excellence?",
    "How do you manage marketing across different time zones and cultures?",
    "What is your approach to marketing transformation?",
    "How do you lead a digital transformation in marketing?",
    "How do you change the culture of a marketing organization?",
    "What is your framework for organizational change management in marketing?",
    "How do you handle resistance to change in marketing?",
    "What is your approach to marketing capability building?",
    "How do you assess marketing team capabilities?",
    "How do you close skills gaps in the marketing team?",
    "What is your vision for the future of marketing?",
    "How do you think AI will change marketing leadership?",
    "What is your approach to building an AI-first marketing organization?",
    "How do you prepare your team for the future of marketing?",
    "What is your experience with Web3 marketing?",
    "How do you approach metaverse strategy?",
    "What is your perspective on blockchain in marketing?",
    "How do you evaluate emerging technologies for marketing?",
    "What is your approach to data strategy in marketing?",
    "How do you build a data-driven marketing organization?",
    "How do you create a data culture in marketing?",
    "What is your approach to marketing technology architecture?",
    "How do you manage a marketing technology budget?",
    "How do you evaluate build vs buy for marketing tech?",
    "What is your experience with marketing platforms at scale?",
    "How do you select a marketing cloud platform?",
    "What is your approach to vendor consolidation in marketing tech?",
    "How do you manage marketing integration complexity?",
    "What is your approach to marketing ROI at the enterprise level?",
    "How do you measure the business impact of marketing?",
    "How do you connect marketing activities to revenue?",
    "What is your approach to marketing investment optimization?",
    "How do you build a marketing ROI model?",
    "How do you justify marketing investment to the board?",
    "What is your experience with zero-based budgeting in marketing?",
    "How do you allocate marketing resources for maximum impact?",
    "How do you optimize marketing spend across the funnel?",
    "What is your approach to brand strategy at the enterprise level?",
    "How do you build global brand equity?",
    "How do you manage a global brand portfolio?",
    "What is your approach to house of brands vs branded house?",
    "How do you manage brand architecture across multiple brands?",
    "What is your experience with brand valuation?",
    "How do you increase brand value?",
    "How do you measure brand contribution to enterprise value?",
    "What is your approach to customer strategy?",
    "How do you build a customer-centric marketing organization?",
    "How do you create a customer experience strategy?",
    "How do you measure customer experience across touchpoints?",
    "What is your approach to customer lifetime value optimization?",
    "How do you build a loyalty ecosystem?",
    "How do you create an advocacy engine?",
    "What is your approach to growth strategy through marketing?",
    "How do you identify growth opportunities through marketing?",
    "How do you create a growth marketing function?",
    "What is your experience with scalling growth marketing?",
    "How do you balance acquisition, retention, and expansion?",
    "How do you drive repeatable and scalable growth?",
    "What is your approach to competitive strategy as a marketing leader?",
    "How do you build a competitive advantage through marketing?",
    "How do you respond to competitive disruption?",
    "How do you create category leadership?",
    "How do you build a category creation strategy?",
    "What is your experience with creating new markets?",
    "How do you lead innovation in marketing?",
    "What is your approach to building an innovation pipeline?",
    "How do you create a culture of experimentation?",
    "How do you scale experimentation across marketing?",
    "How do you manage the risk of marketing innovation?",
    "How do you balance innovation with core business?",
    "What is your approach to marketing risk management?",
    "How do you manage brand risk?",
    "How do you ensure marketing compliance at scale?",
    "What is your approach to regulatory affairs in marketing?",
    "How do you navigate complex regulatory environments?",
    "What is your experience with marketing in highly regulated industries?",
    "How do you build trust in marketing at scale?",
    "How do you approach brand purpose and activism?",
    "What is your experience with brand-led social impact?",
    "How do you measure the impact of purpose marketing?",
    "How do you balance stakeholder interests in marketing?",
    "What is your approach to ESG marketing?",
    "How do you communicate sustainability credibly?",
    "How do you build a sustainable marketing practice?",
    "What is your approach to DEI in marketing leadership?",
    "How do you build diverse marketing teams?",
    "How do you ensure inclusive marketing?",
    "What is your approach to ethical marketing at scale?",
    "How do you manage marketing in a polarized world?",
    "How do you navigate political and social issues as a brand?",
    "What is your approach to crisis leadership in marketing?",
    "How do you lead through a major brand crisis?",
    "How do you rebuild a damaged brand?",
    "What is your approach to long-term brand resilience?",
    "How do you build a brand that lasts generations?",
]

print(f"\nManager Intern: {len(manager_intern)}")
print(f"Manager Fresher: {len(manager_fresher)}")
print(f"Manager Junior: {len(manager_junior)}")
print(f"Manager Middle: {len(manager_middle)}")
print(f"Manager Senior: {len(manager_senior)}")

# =============================================
# Combine scraped questions into appropriate levels
# =============================================

# Classify scraped questions into levels based on complexity
def classify_level(q):
    ql = q.lower()
    # Senior indicators
    senior_keywords = ['3-5 year', '5 year', 'board', 'transformation', 'c-suite', 'cfo', 'organization',
                       'enterprise', 'global', 'acquisition', 'ipo', 'merger', 'vision', 'evp',
                       'chief', 'vp of', 'director of', 'head of']
    # Middle indicators
    middle_keywords = ['team', 'budget', 'strategy', 'manage', 'lead', 'mentor', 'cross-functional',
                       'stakeholder', 'vendor', 'agency', 'roadmap', 'portfolio', 'scale',
                       'integrate', 'align', 'optimize', 'attribution', 'framework']
    # Junior indicators
    junior_keywords = ['campaign', 'analyze', 'measure', 'report', 'execute', 'segment',
                       'create', 'develop', 'implement', 'run', 'tool', 'platform',
                       'google analytics', 'a/b test', 'ab test', 'social media', 'email']
    
    # Simple/basic questions = intern/fresher level
    basics = ['what is', 'define', 'meaning', 'difference between', 'explain', 'list']
    
    # Count matches
    senior_score = sum(1 for k in senior_keywords if k in ql)
    middle_score = sum(1 for k in middle_keywords if k in ql) 
    junior_score = sum(1 for k in junior_keywords if k in ql)
    basic_score = sum(1 for k in basics if k in ql[:30])
    
    if basic_score > 0 and senior_score == 0 and middle_score == 0:
        return 'Intern'
    elif junior_score > 0 and middle_score == 0 and senior_score == 0:
        return 'Junior'
    elif middle_score > junior_score and senior_score == 0:
        return 'Middle'
    elif senior_score > 0:
        return 'Senior'
    elif basic_score > 0:
        return 'Fresher'
    elif junior_score > 0:
        return 'Junior'
    else:
        return 'Junior'  # default

# Distribute scraped questions
scraped_by_level = {'Intern': [], 'Fresher': [], 'Junior': [], 'Middle': [], 'Senior': []}
for q in scraped_clean:
    level = classify_level(q)
    scraped_by_level[level].append(q)

print(f"\nScraped distribution: { {k: len(v) for k, v in scraped_by_level.items()} }")

# =============================================
# Build final datasets
# =============================================

def ensure_count(qlist, target=100):
    """Ensure list has at least target questions."""
    return list(set(qlist))  # Already have >= 100

specialist_data = {
    "position": "Marketing Specialist",
    "questions": {
        "Intern": ensure_count(specialist_intern),
        "Fresher": ensure_count(specialist_fresher),
        "Junior": ensure_count(specialist_junior),
        "Middle": ensure_count(specialist_middle),
        "Senior": ensure_count(specialist_senior),
    }
}

manager_data = {
    "position": "Marketing Manager",
    "questions": {
        "Intern": ensure_count(manager_intern),
        "Fresher": ensure_count(manager_fresher),
        "Junior": ensure_count(manager_junior),
        "Middle": ensure_count(manager_middle),
        "Senior": ensure_count(manager_senior),
    }
}

# Count totals
spec_total = sum(len(v) for v in specialist_data['questions'].values())
mgr_total = sum(len(v) for v in manager_data['questions'].values())
print(f"\nSpecialist total: {spec_total}")
print(f"Manager total: {mgr_total}")
print(f"Grand total: {spec_total + mgr_total}")

# Verify minimums
all_ok = True
for pos_name, pos_data in [("Specialist", specialist_data), ("Manager", manager_data)]:
    for level, qs in pos_data['questions'].items():
        count = len(qs)
        status = "OK" if count >= 100 else "SHORT"
        if count < 100:
            all_ok = False
        print(f"  {pos_name} / {level}: {count} questions [{status}]")

# Save
with open('/home/nhatbang/EXE101/PRJ/docs/crawl_data/marketing_specialist.json', 'w') as f:
    json.dump(specialist_data, f, indent=2)

with open('/home/nhatbang/EXE101/PRJ/docs/crawl_data/marketing_manager.json', 'w') as f:
    json.dump(manager_data, f, indent=2)

print("\nFiles saved successfully!")
print(f"\nAll minimums met: {all_ok}")
